name: mr_coffee
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # firebase
  firebase_core: ^3.8.0

  # core
  connectivity_plus: ^6.1.0
  flutter_dotenv: ^5.2.1
  flutter_screenutil: ^5.9.3
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.3
  cached_network_image: ^3.4.1
  flutter_spinkit: ^5.2.1
  crystal_navigation_bar: ^1.0.2
  iconly: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true


  assets:
    - .env.dev
    - .env.prod
    - assets/images/logo.png

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo_font/Cairo-Regular.ttf
        - asset: assets/fonts/cairo_font/Cairo-Bold.ttf
          # style: italic
          weight: 900


flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png
  android_12:
    color: "#FFFFFF"
    image: assets/images/logo.png
